# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Release
on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: build dist
      run: |
        python setup.py sdist
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: |
        npm install @semantic-release/commit-analyzer \
                    @semantic-release/release-notes-generator \
                    @semantic-release/github \
                    semantic-release
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release -e ./.github/.releaserc.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine==4.0.1
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        twine check dist/*.tar.gz
        twine upload \
          --skip-existing \
          --verbose \
          dist/*.tar.gz
